jetty:
  context: /hello
  connectors:
    - port: 8080
      #java -jar target/BootiqueMavenTestProject-1.0-SNAPSHOT.jar --server --config=./src/main/resources/myconfig.yaml
      #java -jar target/bootique-maven-test-project-1.0-SNAPSHOT.jar --server --config=./src/main/resources/myconfig.yaml
